import { boolean, index, integer, jsonb, pgEnum, pgTable, text, timestamp, uniqueIndex, uuid } from 'drizzle-orm/pg-core';
import { EVENT_CATEGORIES, EVENT_SEVERITIES, EVENT_STATUSES, VERIFICATION_STATUSES } from '@/domain/events/constants';

export const categoryEnum = pgEnum('event_category', EVENT_CATEGORIES);
export const statusEnum = pgEnum('event_status', EVENT_STATUSES);
export const severityEnum = pgEnum('event_severity', EVENT_SEVERITIES);
export const verificationEnum = pgEnum('verification_status', VERIFICATION_STATUSES);
export const sourceTypeEnum = pgEnum('source_type', ['official_website', 'rss', 'api', 'html', 'pdf', 'social', 'manual', 'other']);
export const candidateStatusEnum = pgEnum('candidate_status', ['pending', 'approved', 'rejected', 'merged']);

export const events = pgTable('events', { id: uuid('id').defaultRandom().primaryKey(), slug: text('slug').notNull(), title: text('title').notNull(), summary: text('summary').notNull(), description: text('description').notNull(), category: categoryEnum('category').notNull(), status: statusEnum('status').notNull(), severity: severityEnum('severity').notNull(), startsAt: timestamp('starts_at', { withTimezone: true }).notNull(), endsAt: timestamp('ends_at', { withTimezone: true }), isAllDay: boolean('is_all_day').notNull().default(false), affectedServices: text('affected_services').array().notNull().default([]), affectedLocations: text('affected_locations').array().notNull().default([]), municipality: text('municipality'), district: text('district'), country: text('country').notNull().default('PT'), sourceConfidence: integer('source_confidence').notNull().default(50), verificationStatus: verificationEnum('verification_status').notNull().default('reviewed'), lastVerifiedAt: timestamp('last_verified_at', { withTimezone: true }), createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(), updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull() }, (t) => [uniqueIndex('events_slug_uq').on(t.slug), index('events_slug_idx').on(t.slug), index('events_starts_idx').on(t.startsAt), index('events_ends_idx').on(t.endsAt), index('events_category_idx').on(t.category), index('events_status_idx').on(t.status), index('events_severity_idx').on(t.severity), index('events_district_idx').on(t.district), index('events_municipality_idx').on(t.municipality), index('events_verification_idx').on(t.verificationStatus)]);

export const sources = pgTable('sources', { id: uuid('id').defaultRandom().primaryKey(), name: text('name').notNull(), slug: text('slug').notNull(), url: text('url').notNull(), type: sourceTypeEnum('type').notNull(), country: text('country').notNull().default('PT'), reliability: integer('reliability').notNull().default(50), adapterKey: text('adapter_key').notNull(), isActive: boolean('is_active').notNull().default(true), lastCheckedAt: timestamp('last_checked_at', { withTimezone: true }), createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(), updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull() }, (t) => [uniqueIndex('sources_slug_uq').on(t.slug), uniqueIndex('sources_adapter_uq').on(t.adapterKey), index('sources_adapter_idx').on(t.adapterKey)]);

export const eventSources = pgTable('event_sources', { id: uuid('id').defaultRandom().primaryKey(), eventId: uuid('event_id').notNull().references(() => events.id, { onDelete: 'cascade' }), url: text('url').notNull(), title: text('title'), publisher: text('publisher'), sourceType: sourceTypeEnum('source_type').notNull(), retrievedAt: timestamp('retrieved_at', { withTimezone: true }).notNull(), rawTextSnippet: text('raw_text_snippet'), confidence: integer('confidence').notNull().default(50), createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull() }, (t) => [index('event_sources_event_idx').on(t.eventId)]);

export const ingestionRuns = pgTable('ingestion_runs', { id: uuid('id').defaultRandom().primaryKey(), sourceId: uuid('source_id').references(() => sources.id), adapterKey: text('adapter_key').notNull(), status: text('status').notNull(), startedAt: timestamp('started_at', { withTimezone: true }).notNull(), finishedAt: timestamp('finished_at', { withTimezone: true }), error: text('error'), eventsFound: integer('events_found').notNull().default(0), candidatesCreated: integer('candidates_created').notNull().default(0), createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull() }, (t) => [index('ingestion_runs_adapter_idx').on(t.adapterKey)]);

export const candidateEvents = pgTable('candidate_events', { id: uuid('id').defaultRandom().primaryKey(), ingestionRunId: uuid('ingestion_run_id').notNull().references(() => ingestionRuns.id, { onDelete: 'cascade' }), sourceId: uuid('source_id').references(() => sources.id), rawPayload: jsonb('raw_payload').notNull(), normalizedPayload: jsonb('normalized_payload').notNull(), status: candidateStatusEnum('status').notNull().default('pending'), duplicateOfEventId: uuid('duplicate_of_event_id').references(() => events.id), reviewerId: text('reviewer_id'), reviewedAt: timestamp('reviewed_at', { withTimezone: true }), createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull() }, (t) => [index('candidate_events_status_idx').on(t.status)]);

export const auditLogs = pgTable('audit_logs', { id: uuid('id').defaultRandom().primaryKey(), actorId: text('actor_id'), action: text('action').notNull(), entityType: text('entity_type').notNull(), entityId: text('entity_id').notNull(), metadata: jsonb('metadata').notNull().default({}), createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull() });
